packages:
  - docs
  - packages/*

catalog:
  '@axe-core/playwright': 4.11.0
  '@biomejs/biome': 2.3.11
  '@chromatic-com/storybook': 4.1.3
  '@commitlint/cli': 20.3.1
  '@commitlint/config-conventional': 20.3.1
  '@cyclonedx/cyclonedx-npm': 4.1.2
  '@docusaurus/core': 3.9.2
  '@docusaurus/module-type-aliases': 3.9.2
  '@docusaurus/plugin-client-redirects': ^3.9.2
  '@docusaurus/plugin-ideal-image': ^3.9.2
  '@docusaurus/plugin-pwa': ^3.9.2
  '@docusaurus/preset-classic': 3.9.2
  '@docusaurus/theme-live-codeblock': ^3.9.2
  '@docusaurus/theme-mermaid': 3.9.2
  '@docusaurus/tsconfig': 3.9.2
  '@docusaurus/types': 3.9.2
  '@easyops-cn/docusaurus-search-local': ^0.52.2
  '@fast-check/vitest': 0.2.4
  '@mdx-js/react': 3.1.1
  '@playwright/experimental-ct-react': 1.57.0
  '@playwright/test': 1.57.0
  '@redocly/cli': 2.14.5
  '@secretlint/secretlint-rule-preset-recommend': 11.2.5
  '@storybook/addon-a11y': 10.1.11
  '@storybook/addon-designs': 11.1.1
  '@storybook/addon-docs': 10.1.11
  '@storybook/addon-mcp': 0.1.8
  '@storybook/addon-onboarding': 10.1.11
  '@storybook/addon-themes': 10.1.11
  '@storybook/addon-vitest': 10.1.11
  '@storybook/mdx2-csf': 1.1.0
  '@storybook/nextjs': 10.1.11
  '@storybook/nextjs-vite': 10.1.11
  '@storybook/react': 10.1.11
  '@storybook/test-runner': 0.24.2
  '@stryker-mutator/core': 9.4.0
  '@stryker-mutator/typescript-checker': 9.4.0
  '@stryker-mutator/vitest-runner': 9.4.0
  '@t3-oss/env-core': 0.13.10
  '@testing-library/jest-dom': 6.6.4
  '@testing-library/react': 16.2.0
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@textlint/textlint-plugin-markdown': 15.5.0
  '@types/node': 25.0.6
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@vitest/browser-playwright': 4.0.17
  '@vitest/coverage-v8': 4.0.17
  ajv: 8.17.1
  bats: 1.13.0
  bats-assert: 2.2.4
  bats-support: 0.3.0
  chromatic: 13.3.5
  clsx: 2.1.1
  dependency-cruiser: 17.3.6
  docusaurus-plugin-image-zoom: ^3.0.1
  docusaurus-plugin-typedoc: ^1.4.2
  docusaurus-theme-github-codeblock: ^2.0.2
  fast-check: 4.5.3
  jsdom: 26.1.0
  knip: 5.80.2
  lefthook: 2.0.14
  playwright: 1.57.0
  playwright-bdd: 8.4.2
  prism-js: ^1.0.0
  prism-react-renderer: 2.4.1
  raw-loader: 4.0.2
  react: 19.2.3
  react-dom: 19.2.3
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  secretlint: 11.2.5
  storybook: 10.1.11
  ts-node: 10.9.2
  typedoc: 0.28.16
  typedoc-plugin-markdown: ^4.9.0
  typedoc-plugin-merge-modules: 7.0.0
  typedoc-theme-hierarchy: 6.0.0
  typescript: 5.9.3
  vitest: 4.0.17

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
  - libxmljs2
  - msw
  - sharp
  - unrs-resolver

peerDependencyRules:
  allowedVersions:
    react: '19'
  ignoreMissing:
    - react

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
